-- econ-engine/sql/setup.sql

-- 1) econ_events
create table if not exists public.econ_events (
  id bigint primary key generated by default as identity,
  event_id text unique,
  event_name text not null,
  currency text,
  impact text check (impact in ('low','medium','high')),
  date_utc timestamptz not null,
  forecast text,
  previous text,
  source text not null,
  created_at timestamptz default timezone('utc', now()),
  updated_at timestamptz default timezone('utc', now())
);

create index if not exists idx_econ_events_date on public.econ_events (date_utc);

-- 2) economic_calendar_alerts
create table if not exists public.economic_calendar_alerts (
  id uuid primary key default gen_random_uuid(),
  event_id text not null,
  title text not null,
  alert_type text not null,
  event_time timestamptz not null,
  sent_at timestamptz default timezone('utc', now())
);

create index if not exists idx_econ_alerts_eventid on public.economic_calendar_alerts (event_id);

-- RLS
alter table public.econ_events enable row level security;

drop policy if exists select_public_econ on public.econ_events;
drop policy if exists service_role_write_econ on public.econ_events;

create policy select_public_econ on public.econ_events 
  for select using (true);

create policy service_role_write_econ on public.econ_events
  for all to service_role using (true) with check (true);

alter table public.economic_calendar_alerts enable row level security;

drop policy if exists service_role_write_alerts on public.economic_calendar_alerts;

create policy service_role_write_alerts on public.economic_calendar_alerts
  for insert to service_role using (auth.role() = 'service_role') with check (auth.role() = 'service_role');